# Generated by Django 4.0.1 on 2022-03-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccineneedy',
            name='is_mailed',
            field=models.BooleanField(default=False),
        ),
    ]
