# Generated by Django 4.0.1 on 2022-03-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodgroup',
            name='min_stock',
            field=models.IntegerField(default=5),
        ),
    ]
