# Generated by Django 4.0.1 on 2022-03-16 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0002_bloodgroup_min_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodgroup',
            name='min_stock',
        ),
    ]
